api:
  cors:
    allowed:
      origins: '*'
      methods: GET,PUT,POST,DELETE

logging:
  level:
    org:
      hibernate:
        cache:
          ehcache:
            internal: trace
          internal: trace
          spi: trace
        orm:
          jdbc:
            bind: trace
        SQL: debug
    net:
      ttddyy:
        dsproxy:
          listener: info # set to 'debug' for some kick-ass SQL logs
    root: INFO

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: a.posto.interactive.dmm.backend.core.config.SnakeCasePhysicalNamingStrategy
#    properties:
#      hibernate:
#        cache:
#          infinispan:
#            cfg: org/infinispan/hibernate/cache/commons/builder/infinispan-configs-local.xml
#          use_second_level_cache: true
#          region:
#            factory_class: org.infinispan.hibernate.cache.v60.InfinispanRegionFactory
    show-sql: false