api:
  cors:
    allowed:
      origins: '*'
      methods: GET,PUT,POST,DELETE

application:
  label: Dump Master Melito

logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: info # set to 'debug' for some kick-ass SQL logs
    root: INFO

server:
  servlet:
    context-path: /dump-master-melito

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: a.posto.interactive.dmm.backend.core.config.SnakeCasePhysicalNamingStrategy
    show-sql: false
  profiles:
    active: production # either development or production
  sql:
    init:
      data-locations: classpath:data/init-data.sql