api:
  cors:
    allowed:
      origins: '*'
      methods: GET,PUT,POST,DELETE

logging:
  level:
    org:
      hibernate:
        cache:
          ehcache:
            internal: trace
          internal: trace
          spi: trace
    net:
      ttddyy:
        dsproxy:
          listener: debug # set to 'debug' for some kick-ass SQL logs
    root: INFO

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: a.posto.interactive.dmm.backend.core.config.SnakeCasePhysicalNamingStrategy
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: jcache
      javax:
        cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
    show-sql: false