application:
  label: Dump-Master Melito

server:
  servlet:
    context-path: /dump-master-melito

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: a.posto.interactive.dmm.backend.core.config.SnakeCasePhysicalNamingStrategy
  profiles:
    active: development
  sql:
    init:
      data-locations: classpath:data/init-data.sql