api:
  cors:
    allowed:
      origins: '*'
      methods: GET,PUT,POST,DELETE

logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: info # set to 'debug' for some kick-ass SQL logs
    root: INFO

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: a.posto.interactive.dmm.backend.core.config.SnakeCasePhysicalNamingStrategy
    show-sql: false